# Generated by Django 4.2.23 on 2025-07-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_city_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
