# Generated by Django 4.2.23 on 2025-07-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='time_event',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
