# Generated by Django 4.2.23 on 2025-08-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientfavouritebarbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
