# Generated by Django 4.2.23 on 2025-10-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0011_barberschedule_external_id_barberservice_duration_and_more'),
        ('client', '0005_client_blocked_client_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequest',
            old_name='time_event',
            new_name='from_time',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='score',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='service',
        ),
        migrations.AddField(
            model_name='client',
            name='external_id',
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='selected_barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_clients', to='barber.barber'),
        ),
        migrations.AddField(
            model_name='client',
            name='selected_request_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='selected_schedule_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='barber_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='barber.barberschedule'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='external_id',
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='overall_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='barber.barber'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='client.client'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('deny', 'Deny'), ('done', 'Done'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='clientfavouritebarbers',
            unique_together={('client', 'barber')},
        ),
        migrations.CreateModel(
            name='ClientRequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('external_id', models.BigIntegerField(db_index=True, null=True, unique=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('barber_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='barber.barberservice')),
                ('client_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='client.clientrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
