# Generated by Django 4.2.23 on 2025-07-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientrequest'),
        ('barber', '0003_barberservicescore'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberservicescore',
            name='client_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientrequest'),
        ),
        migrations.AddField(
            model_name='barberservicescore',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
