# Generated by Django 4.2.23 on 2025-07-30 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientrequest'),
        ('barber', '0004_barberservicescore_client_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('day', models.DateField()),
                ('n_clients', models.IntegerField(default=0)),
                ('total_income', models.IntegerField(default=0)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barber')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarberScheduleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('barber_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barberschedule')),
                ('client_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
