# Generated by Django 4.2.23 on 2025-07-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_barberschedule_barberscheduledetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
