# Generated by Django 4.2.23 on 2025-07-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0006_alter_barber_end_time_alter_barber_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='working_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
