# Generated by Django 4.2.23 on 2025-07-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientrequest'),
        ('barber', '0007_alter_barber_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberservicescore',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
