# Generated by Django 4.2.23 on 2025-08-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0008_alter_barberservicescore_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='barber/'),
        ),
        migrations.AddField(
            model_name='barber',
            name='midnight_sum',
            field=models.IntegerField(default=0),
        ),
    ]
