# Generated by Django 4.2.23 on 2025-08-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0009_barber_img_barber_midnight_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='midnight_sum',
            new_name='midnight_price',
        ),
    ]
