# Generated by Django 4.2.23 on 2025-10-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_options_remove_service_description_and_more'),
        ('barber', '0010_rename_midnight_sum_barber_midnight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberschedule',
            name='external_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='external_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='barberservice',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='barber.barber'),
        ),
        migrations.AlterField(
            model_name='barberservice',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='service.service'),
        ),
    ]
