# Generated by Django 4.2.23 on 2025-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Uzbek)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Uzbek)'),
        ),
    ]
