# Generated by Django 4.2.23 on 2025-10-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_options_remove_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
        ),
    ]
