# Generated by Django 4.2.23 on 2025-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('barber', 'barber'), ('admin', 'admin')], default='user', max_length=20),
        ),
    ]
