# Generated by Django 4.2.23 on 2025-07-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='test',
        ),
    ]
