# Generated by Django 4.2.23 on 2025-07-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_telegram_id_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barbers',
        ),
    ]
